Stamp cfdi excutable
yusent/cfdis pull request #19
Opened 2018-06-22 04:43 UTC by yusent

Closes #17

2018-06-30 17:49 UTC, aguilaclc commented
The `xml` header should have the `encoding` attribute set to `UTF-8`

2018-07-01 02:13 UTC, yusent commented
`encoding` attribute was added in e7c9db6dd6069b0b02bc2ed05950ce14e28198d6

2018-07-14 15:33 UTC, AlanGCruz requested changes

2018-07-14 15:33 UTC, AlanGCruz commented on src/CFDI/PAC/Dummy.hs
> +      { psLegend = Just $ SatLegend "No olvide pagar sus impuestos para mantener el Status Quo."
El attributo "Leyenda" no acepta puntos, asi que este mensaje no pasa la validación de esquema.
http://omawww.sat.gob.mx/sitio_internet/cfd/timbrefiscaldigital/TimbreFiscalDigitalv11.xsd

2018-07-14 15:35 UTC, AlanGCruz commented on src/CFDI/PAC/Dummy.hs
> +      { psLegend = Just $ SatLegend "No olvide pagar sus impuestos para mantener el Status Quo."
Si gustas te puedo mandar el PR

2018-07-14 15:37 UTC, yusent commented on src/CFDI/PAC/Dummy.hs
> +      { psLegend = Just $ SatLegend "No olvide pagar sus impuestos para mantener el Status Quo."
Adelante.

2018-07-14 19:07 UTC, yusent commented on stamp/main.hs
> +import CFDI.PAC.ITimbre (ITimbre(ITimbre), ITimbreEnv(Production))
We should have the option to stamp in a testing environment.

2019-06-15 16:54 UTC, merged